services:
  - type: worker
    name: gemini-store-bot
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    disk:
      name: store-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: API_BASE_URL
        value: https://api.hewhotries.tech/v1
      - key: DATA_DIR
        value: /data
